// <auto-generated />
using System;
using DiplomskiRAD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiplomskiRAD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250212114817_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiplomskiRAD.Models.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<int>("EquipmentState")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slika")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("DiplomskiRAD.Models.Motorcycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<double>("Kilometraza")
                        .HasColumnType("double precision");

                    b.Property<int>("MotorcycleState")
                        .HasColumnType("integer");

                    b.Property<int>("MotorcycleType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slika")
                        .HasColumnType("text");

                    b.Property<int>("YearOfProduction")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Motorcycles");
                });

            modelBuilder.Entity("DiplomskiRAD.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("OrderAmount")
                        .HasColumnType("double precision");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DiplomskiRAD.Models.PriceList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StartingDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PriceLists");
                });

            modelBuilder.Entity("DiplomskiRAD.Models.Producer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Producers");
                });

            modelBuilder.Entity("DiplomskiRAD.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<double?>("Salary")
                        .HasColumnType("double precision");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("numOfPurchases")
                        .HasColumnType("integer");

                    b.Property<int>("numOfTasks")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EquipmentOrder", b =>
                {
                    b.Property<Guid>("EquipmentsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrdersId")
                        .HasColumnType("uuid");

                    b.HasKey("EquipmentsId", "OrdersId");

                    b.HasIndex("OrdersId");

                    b.ToTable("EquipmentOrder");
                });

            modelBuilder.Entity("EquipmentPriceList", b =>
                {
                    b.Property<Guid>("EquipmentsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PriceListsId")
                        .HasColumnType("uuid");

                    b.HasKey("EquipmentsId", "PriceListsId");

                    b.HasIndex("PriceListsId");

                    b.ToTable("EquipmentPriceList");
                });

            modelBuilder.Entity("EquipmentProducer", b =>
                {
                    b.Property<Guid>("EquipmentsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProducersId")
                        .HasColumnType("uuid");

                    b.HasKey("EquipmentsId", "ProducersId");

                    b.HasIndex("ProducersId");

                    b.ToTable("EquipmentProducer");
                });

            modelBuilder.Entity("MotorcycleOrder", b =>
                {
                    b.Property<Guid>("MotorcyclesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrdersId")
                        .HasColumnType("uuid");

                    b.HasKey("MotorcyclesId", "OrdersId");

                    b.HasIndex("OrdersId");

                    b.ToTable("MotorcycleOrder");
                });

            modelBuilder.Entity("MotorcyclePriceList", b =>
                {
                    b.Property<Guid>("MotorcyclesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PriceListsId")
                        .HasColumnType("uuid");

                    b.HasKey("MotorcyclesId", "PriceListsId");

                    b.HasIndex("PriceListsId");

                    b.ToTable("MotorcyclePriceList");
                });

            modelBuilder.Entity("MotorcycleProducer", b =>
                {
                    b.Property<Guid>("MotorcyclesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProducersId")
                        .HasColumnType("uuid");

                    b.HasKey("MotorcyclesId", "ProducersId");

                    b.HasIndex("ProducersId");

                    b.ToTable("MotorcycleProducer");
                });

            modelBuilder.Entity("DiplomskiRAD.Models.Order", b =>
                {
                    b.HasOne("DiplomskiRAD.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EquipmentOrder", b =>
                {
                    b.HasOne("DiplomskiRAD.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomskiRAD.Models.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EquipmentPriceList", b =>
                {
                    b.HasOne("DiplomskiRAD.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomskiRAD.Models.PriceList", null)
                        .WithMany()
                        .HasForeignKey("PriceListsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EquipmentProducer", b =>
                {
                    b.HasOne("DiplomskiRAD.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomskiRAD.Models.Producer", null)
                        .WithMany()
                        .HasForeignKey("ProducersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MotorcycleOrder", b =>
                {
                    b.HasOne("DiplomskiRAD.Models.Motorcycle", null)
                        .WithMany()
                        .HasForeignKey("MotorcyclesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomskiRAD.Models.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MotorcyclePriceList", b =>
                {
                    b.HasOne("DiplomskiRAD.Models.Motorcycle", null)
                        .WithMany()
                        .HasForeignKey("MotorcyclesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomskiRAD.Models.PriceList", null)
                        .WithMany()
                        .HasForeignKey("PriceListsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MotorcycleProducer", b =>
                {
                    b.HasOne("DiplomskiRAD.Models.Motorcycle", null)
                        .WithMany()
                        .HasForeignKey("MotorcyclesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomskiRAD.Models.Producer", null)
                        .WithMany()
                        .HasForeignKey("ProducersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiplomskiRAD.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
